version: '3.1'
services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /home/user/grainpath/db:/data/db
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm
    ports:
      - 27018:5000
    volumes:
      - /home/user/grainpath/osrm:/data
    command: "osrm-routed --max-viaroute-size 500 --max-table-size 500 --algorithm mld /data/czech-republic-latest.osrm"
